package.json, routes/usuario.routes.js
Se agregó una validación para que el correo solicitado sea de un correo de Google
=> Verificar correo

controllers/authController.js, routes/authRoutes.js, services/authService.js
Se ha implementado la autenticación con Google utilizando OAuth 2.0.
=> Implementación de autenticación con Google

controllers/main.controller.js
Se ha creado el main.controller.js, siendo el controlador principal de la aplicación.
=> Creación del main.controller.js

routes/main.routes.js
Se ha creado main.routes.js, siendo el modulo de control de rutas principal de la aplicación.
=> Creación de main.main.js

controllers/main.controller.js, routes/main.routes.js, views/header.ejs
Se ha creado la sidebar que será utilizada en todas las vistas de la aplicación.
=> Creación de sidebar

util/generarID.js
Se ha creado un módulo para generar IDs para la base de datos.
=> Crear generador de id

f, util/encryptData.js
Se ha creado un módulo para encriptar datos sensibles que se alamacenen en la base de datos.
=> Crear modulo de encriptacion de datos

public/styles.css
Modificar el padding para mejorar el espacio en el sidebar.
=> Arrgelar espacio en iconos del sidebar.

public/styles.css
Se ha creado un modulo de los contenedores para los formularios. Estos contenedores forman parte del aspecto visual de las vista. Se cambio nada mas el css. Favor de revisar los cambios en la documentacion pertinente.
=> Modulo de contenedores vistas

package.json, sql/soffy.sql, util/database.js
1. Util para manejar las conexiones con la base de datos
2. SQL para su base de datos local
=> conexion db y sql

controllers/educacion.controller.js, models/educacion.model.js, public/js/educacion.js, routes/educacion.routes.js, util/database.js, views/educacion.ejs
Se agrego lógica dentro de la vista donde se desplegaran los alumnos, tanto en modelo, controlador y rutas, además se agrego la funcionalidad al botón de consultar y ya se muestran datos que se encuentran en nuestra base de datos
=> Agregar lógica a la vista de Estudiantes

app.js, routes/pdf.routes.js
Implementar rutas de subida y descarga de archivos PDF.
=> Implementación de rutas.

util/s3Client.js
Implementar módulo para la conexión al S3.
=> Implementación de conexión al S3.

public/js/materias.js, views/materias.ejs
Arreglo con el slavado de modificar materia
=> Arreglo en Modificar Materia

controllers/pacientes.controller.js
Se arregla un bug presente en la interface de pacientes,los botones de eliminar, editar y registrar expediente tenian fallas al momento de redirigirse a su respectivo id de expediente.
Este hotfix se afecta la ruta /pacientes.
=> Se arregla un bug presente en los botones del area de pacientes

controllers/pacientes.controller.js, controllers/psicologia.controller.js, models/pacientes.model.js, util/encryptData.js, views/editarPaciente.ejs, views/partials/head.ejs
Se añade la encriptacion de datos con las claves del .env.  Se hace una modificacion a la base de datos, aumentando el numero de caracteres al doble en la informacion personal. Se corrigio la ruta para llegar a la interfaz de pacientes.
=> Hot fix proteccion datos

app.js, middlewares/loadUserFromJWT.js, public/styles.css, views/home.ejs
=> Cambiar imagen home

controllers/rol.controller.js, models/rolPriv.model.js, public/js/roles.js, routes/rol.routes.js, views/roles.ejs
- **rol by id**
- **obtener rol controler, modelo y ruta**
- **modal terminado**
- **nombre repetido mensaje**
=> Editar Rol

controllers/rol.controller.js, models/rolPriv.model.js, public/js/roles.js, routes/rol.routes.js
- **modelo terminado**
- **controlador y ruta terminado**
- **modal terminado**
- **error en la alerta**
- **correción modelo**
=> Eliminar Rol

services/auth.service.js
Generar Tokens de JWT correctamente, se corrigió una función.
=> Generar Tokens correctamente.

views/partials/head.ejs
Se agrego Centro educativo en la sidebar para una redirección inmediata a la página de Centro Educativo
=> Agregar Centro Edu a SideBar

models/educacion.model.js, views/boletas.ejs
Existian errores por modificaciones en la base de datos, por lo que se arreglo haciendo pequeños cambios de nombres
=> Arreglo de Errores en Boletas

controllers/usuarios.controller.js, models/usuarios.model.js, public/js/usuarios.js, public/styles.css, routes/usuarios.routes.js, views/usuarios.ejs
Encriptación usuarios, agregar roles y validaciones extra
=> Encriptación usuarios, agregar roles y validaciones extra

models/educacion.model.js, public/js/boletas.js, public/js/materias.js, views/boletas.ejs, views/materias.ejs
Existian algunos errores por la modificación de la base de datos, además se implemento la desencriptación de datos, dejando 100% funcional materias. boletas y alumnos
=> Arreglo de Errores Boletas

public/js/boletas.js, public/js/educacion.js, public/js/materias.js, public/styles.css, views/boletas.ejs, views/educacion.ejs, views/materias.ejs
Existian incosistencias en cuanto a las vistas del centro educativo, por lo que se unificaron y quedaron como las demás vistas
=> Unificación de las Vistas de Centro Educativo

public/js/boletas.js, views/boletas.ejs
Se agregaron la opción de poder agregar más materias al modificar una boleta debido a que no existia
=> Agregar Función al Momento de modificar boleta

controllers/nutricion.controller.js, models/nutricion.model.js, public/js/expedienteNutricion.js, public/styles.css, routes/nutricion.routes.js, views/expediente_nutricion.ejs
Se le metio controladores, models y la vista ya es semi funcional de cierta forma.
=> Haciendo funcional el consultar expediente Psicologico

app.js, controllers/authController.js, middlewares/authenticateJWT.js, routes/auth.routes.js, routes/main.routes.js, views/login.ejs
Se cambiaron las rutas del login.
=> Cambiar rutas.

views/materias.ejs
Se agregaron dropdowns dentro de la parte de los pop ups para registrar y modificar materia, esto con el fin de hacer más eficiente el registro o modificacion de las materias
=> Agregar DropDown en PoprUps de Materias

public/js/editarPaciente.js, public/js/registrarPaciente.js, views/editarPaciente.ejs, views/registrarPaciente.ejs
Se agrega el campo de Preparatoria al registro y edicion de pacientes. Tambien cambia la cantidad de grados que te salen cuando seleccionas Preparatoria(los 3 grados)
=> Se agrega campo de Preparatoria al registro de nuevos pacientes

public/js/expedientePsicologico.js
Se arregla un error en el redireccionamient despues de los seguimiento psicologicos, en los cuales te mandaba a una url diferente
=> Se arregla el redireccionamiento despues de seguimientos

public/js/expedienteNutricion.js, views/expediente_nutricion.ejs
Se arregla el ejs del expediente nutricional cambiando un condicional mal colocado en el expedienteNutricion.ejs. Se recoloca la declaracoin de la tabla de expediente nutricional, debido a que se encontraba en una anidacion.
Se accede mediante http://localhost:3000/nutricion/documentos/1 por ejemplo
=> ya aparece el top bar en la interfaz del expediente nutricional

controllers/authController.js, middlewares/authenticateJWT.js, models/auth.model.js
Se cambiaron los datos del token para su uso en el rbac.
=> Cambiar datos del token.

app.js, controllers/historial.controller.js, controllers/pacientes.controller.js, models/pacientes.model.js, routes/historial.routes.js, views/historialExpedientes.ejs
=> Actividad de expediete

controllers/educacion.controller.js, models/educacion.model.js, public/js/boletas.js, public/js/educacion.js, public/js/materias.js, routes/educacion.routes.js
Se arreglaron ultimos detalles de diseño y demás cosas de Centro Educativo dejando una unificación de vistas como el resto del trabajo.
=> Arreglos en Centro Educativo

controllers/authController.js, middlewares/authenticateJWT.js, routes/auth.routes.js, services/auth.service.js
Se cambió la implementación del req y se modificó la ruta de auth para incluirlo.
=> Arreglar implementación del req.

controllers/nutricion.controller.js, models/nutricion.model.js, public/js/expediente.js, public/js/expedienteNutricion.js, public/js/historiaClinica.js, public/js/historiaClinicaV2.js, routes/nutricion.routes.js, views/expediente_nutricion.ejs, views/historiaClinica.ejs, views/historiaClinicaV2.ejs, views/pdf/historiaClinicaV1.ejs, views/pdf/historiaClinicaV2.ejs
Corrección de errores y guardado de historiales
Creacion de PDF's y descarga de los mismos
Arreglo de botones 
consistencia en general
=> Fix nutricion

controllers/pacientes.controller.js, controllers/psicologia.controller.js, routes/nutricion.routes.js, routes/pacientes.routes.js, temp_seguimiento.html, util/can.js, util/s3Client.js
- **subir al s3**
- **subdividir expediente general**
- **descargar, eliminar y ver pdf de paciente**
- **Previsualización de pdf y descarga de pdf solucionado**
- **PDFs para psicología**
=> Actualizar PDF

controllers/pacientes.controller.js, models/pacientes.model.js, public/js/editarPaciente.js, public/js/registrarPaciente.js, views/editarPaciente.ejs, views/expediente.ejs, views/registrarPaciente.ejs
Se agrega el campo de sexo en la parte del expediente del paciente.
Se arregla un error en donde se intentaba hacer una consulta a un campo que no existe en la base de datos desplegada
=> Hotfix nuevo campo sexo

controllers/authController.js, services/auth.service.js
Arreglar errores de compatibilidad de la app movil.
=> Arreglar errores de compatibilidad de la app movil.

controllers/nutricion.controller.js, models/nutricion.model.js, public/js/expedienteNutricion.js, public/js/historiaClinicaV2.js, views/expediente_nutricion.ejs, views/historiaClinica.ejs, views/historiaClinicaV2.ejs, views/pdf/historiaClinicaV1.ejs, views/pdf/historiaClinicaV2.ejs
Arreglo de errores en generación de pdfs y citar documentos
=> Fix a nutricion

controllers/authController.js, models/auth.model.js
Arreglar error en el req.user donde no se mandaba la informacion del token.
=> Arreglar erroren el req.

views/historiaClinica.ejs, views/partials/pagination.ejs
Arreglo de los botones a la historia clinica v1
=> Arreglo de los botones vista historiaclinica

controllers/authController.js, routes/auth.routes.js, services/auth.service.js, views/login.ejs, views/partials/head.ejs
Eliminar console logs con datos del token.
=> Eliminar consoles logs.

controllers/api.psicologia.controller.js, models/psicologia.model.js
Se arregla el cammel case de las api de psicologia
=> Se arregla el cammel case de las Api
